{
 "title": "Infinispan Embedded",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "service", "label": "service", "query": { "query": "label_values(service)" } },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(cache_size{service=\"$service\"}, pod)"
    }
   },
   {
    "name": "cache_name",
    "label": "Cache Name",
    "query": {
     "query": "label_values(cache_size{service=\"$service\", pod=\"$pod\"},cache)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "StartUp/Reset",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "From Start",
     "type": "stat",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
     "repeat": "pod_name",
     "fieldConfig": { "defaults": { "unit": "dtdhms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cache_start_SECONDS{cache = \"$cache_name\", pod = \"$pod\", service = \"$service\"}"
      }
     ]
    },
    {
     "title": "From Reset",
     "type": "stat",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 1 },
     "repeat": "pod_name",
     "fieldConfig": { "defaults": { "unit": "dtdhms" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "cache_reset_SECONDS{cache = \"$cache_name\", pod = \"$pod\", service = \"$service\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Size",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "cache_size{cache = \"$cache_name\", pod = \"$pod\", service = \"$service\" }",
       "legendFormat": "Total Objects"
      },
      {
       "expr": "cache_memory_size{cache = \"$cache_name\", pod = \"$pod\", service = \"$service\"}",
       "legendFormat": "In Memory Objects"
      },
      {
       "expr": "cache_memory_offHeap{cache = \"$cache_name\", pod = \"$pod\", service = \"$service\"}",
       "legendFormat": "Off-heap Objects"
      }
     ]
    }
   ]
  },
  {
   "title": "Cache Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Amount",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(cache_puts_total{cache = \"$cache_name\", pod = \"$pod\" , service = \"$service\" }[1m])",
       "legendFormat": "puts"
      },
      {
       "expr": "sum(rate(cache_gets_total{cache = \"$cache_name\", pod = \"$pod\" , service = \"$service\"}[1m]))",
       "legendFormat": "gets"
      },
      {
       "expr": "rate(cache_evictions_total{cache = \"$cache_name\", pod = \"$pod\" , service = \"$service\"}[1m])",
       "legendFormat": "evictions"
      }
     ]
    },
    {
     "title": "Latency",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "cache_puts_latency_MILLISECONDS{cache = \"$cache_name\", pod = \"$pod\", service = \"$service\"}",
       "legendFormat": "puts"
      },
      {
       "expr": "cache_gets_latency_MILLISECONDS{cache = \"$cache_name\", pod = \"$pod\", service = \"$service\"}",
       "legendFormat": "gets"
      },
      {
       "expr": "cache_removes_latency_MILLISECONDS{cache = \"$cache_name\", pod = \"$pod\" , service = \"$service\"}",
       "legendFormat": "removes"
      }
     ]
    },
    {
     "title": "Hits/Misses",
     "type": "piechart",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 15 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cache_gets_total{cache=\"$cache_name\",pod=\"$pod\",service=\"$service\",result=\"hit\"}",
       "legendFormat": "hits"
      },
      {
       "expr": "cache_gets_total{cache=\"$cache_name\",pod=\"$pod\",service=\"$service\",result=\"miss\"}",
       "legendFormat": "misses"
      }
     ]
    }
   ]
  }
 ]
}